@echo off
REM ============================================================================
REM  build-all.bat  -  full Realm Engine build, end to end.
REM  This Batch File was AI generated. 
REM
REM      HUMAN WRITTEN - READ THIS!
REM  Requirements: 
REM                Visual Studio 2022 or newer with the C++ x64 tools (the
REM                installed platform toolset is auto-detected), Node.js/npm,
REM                .NET 10 runtime,
REM                tools/Il2CppInspector.exe (build Il2CppInspectorPro **CLI**),
REM                tools/global-metadata.decrypted.dat (https://builds.him.is/latest/game_files/global-metadata.decrypted.dat)
REM       The rest is AI slop feel free to ignore.
REM
REM  Produces a packaged client (installer + portable, or just portable) with
REM  both freshly-built native DLLs baked in:
REM     * realm-engine.dll  (the IL2CPP hack DLL, from internal/)
REM     * winhttp.dll  (from branch client/winhttp-proxy/)  
REM  and freshly-generated IL2CPP headers for the current game build.
REM
REM  Usage:
REM     build-all.bat              installer + portable
REM     build-all.bat portable     portable exe only (faster)
REM
REM  Optional skips (set before running):
REM     set RE_SKIP_HEADERS=1      reuse existing internal/src/game/generated
REM     set RE_SKIP_XML=1          skip the (optional) game-XML download
REM ============================================================================
setlocal enableextensions
set "ROOT=%~dp0"
set "MODE=%~1"

echo.
echo ==================== Realm Engine : full build ====================

REM --- [0/6] Preflight --------------------------------------------------------
echo [0/6] Preflight checks...
if not exist "%ROOT%tools\Il2CppInspector.exe" (
  echo   [ERROR] tools\Il2CppInspector.exe missing. Build the CLI first.
  goto :fail
)
if not exist "%ROOT%tools\global-metadata.decrypted.dat" (
  echo   tools\global-metadata.decrypted.dat missing - downloading...
  curl -fSL -o "%ROOT%tools\global-metadata.decrypted.dat" "https://builds.him.is/latest/game_files/global-metadata.decrypted.dat"
  if errorlevel 1 (
    if exist "%ROOT%tools\global-metadata.decrypted.dat" del /q "%ROOT%tools\global-metadata.decrypted.dat"
    echo   [ERROR] metadata download failed.
    goto :fail
  )
  if not exist "%ROOT%tools\global-metadata.decrypted.dat" ( echo   [ERROR] metadata download produced no file. & goto :fail )
  echo   Downloaded -^> tools\global-metadata.decrypted.dat
)
where npm >nul 2>nul || ( echo   [ERROR] npm not on PATH. Install Node.js. & goto :fail )

set "VSWHERE=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
if not exist "%VSWHERE%" ( echo   [ERROR] Visual Studio Installer not found. Install VS 2022 or newer. & goto :fail )
set "VSINSTALL="
for /f "usebackq tokens=*" %%i in (`"%VSWHERE%" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set "VSINSTALL=%%i"
if not defined VSINSTALL ( echo   [ERROR] VS C++ x64 tools not installed. & goto :fail )
echo   Using Visual Studio: %VSINSTALL%
call "%VSINSTALL%\VC\Auxiliary\Build\vcvars64.bat" >nul || ( echo   [ERROR] vcvars64 setup failed. & goto :fail )
echo   VS x64 environment ready (cl.exe + MSBuild).

REM --- [1/6] IL2CPP headers ---------------------------------------------------
if /I "%RE_SKIP_HEADERS%"=="1" (
  echo [1/6] Skipping IL2CPP header generation ^(RE_SKIP_HEADERS=1^).
) else (
  echo [1/6] Generating IL2CPP headers from the live game...
  powershell -NoProfile -ExecutionPolicy Bypass -File "%ROOT%tools\gen-il2cpp-headers.ps1" || goto :fail
)

REM --- [2/6] realm-engine.dll -------------------------------------------------
echo [2/6] Building realm-engine.dll ^(Release^|x64^)...
REM  Release builds #error without BuildSecrets.h. build-prod.mjs writes it in
REM  step 6, but this earlier standalone build needs it too. Same fixed PUBLIC
REM  constants build-prod.mjs uses - keep the two in sync.
set "SECRETS=%ROOT%internal\src\core\ipc\BuildSecrets.h"
if not exist "%SECRETS%" (
  echo   Writing BuildSecrets.h ^(fixed public constants^)...
  > "%SECRETS%" echo #pragma once
  >>"%SECRETS%" echo // AUTO-GENERATED by build-all.bat - do not edit or commit.
  >>"%SECRETS%" echo #define BUILD_HANDSHAKE_KEY "47eb249907eb980c851fe3a7bdb56a244244bb7d465572b556e810df6827ecfb"
  >>"%SECRETS%" echo #define BUILD_PIPE_NAME "\\\\.\\pipe\\lfg-dev-bridge"
)
msbuild "%ROOT%internal\il2cpp-dll-injection.sln" /p:Configuration=Release /p:Platform=x64 /m /v:minimal /nologo || goto :fail
REM  The vcxproj's OutDir is already client\assets\, so no copy step is needed.
if not exist "%ROOT%client\assets\realm-engine.dll" ( echo   [ERROR] realm-engine.dll not produced. & goto :fail )
echo   Built -^> client\assets\realm-engine.dll

REM --- [3/6] winhttp.dll + injector.exe ---------------------------------------
REM  The proxy sources are optional: when client\winhttp-proxy\ is not present
REM  we fall back to whatever winhttp.dll is already staged in client\assets\
REM  rather than failing the whole build. Only warn if there is no shim at all,
REM  since that produces a package that silently misses the redirect.
if not exist "%ROOT%client\winhttp-proxy\build.bat" (
  echo [3/6] client\winhttp-proxy\build.bat not present - skipping winhttp.dll build.
  if exist "%ROOT%client\assets\winhttp.dll" (
    echo   Using the winhttp.dll already staged in client\assets\.
  ) else (
    echo   [WARN] No winhttp.dll staged in client\assets\ either.
    echo   [WARN] The packaged client will ship without the network shim.
  )
) else (
  echo [3/6] Building winhttp.dll ^(source shim^)...
  REM  build.bat is invoked by explicit path, not by bare name: cmd only
  REM  searches the working directory when NoDefaultCurrentDirectoryInExePath
  REM  is unset, and it is set on some machines. The pushd still matters --
  REM  build.bat resolves its own inputs relative to the working directory.
  pushd "%ROOT%client\winhttp-proxy"
  call ".\build.bat" || ( popd & goto :fail )
  popd
  if not exist "%ROOT%client\winhttp-proxy\winhttp.dll" ( echo   [ERROR] winhttp.dll not produced. & goto :fail )
  copy /y "%ROOT%client\winhttp-proxy\winhttp.dll" "%ROOT%client\assets\winhttp.dll" >nul
  echo   Staged -^> client\assets\winhttp.dll
)

REM  injector.exe — CreateRemoteThread loader that src/native/injector.ts spawns
REM  to inject realm-engine.dll. Single translation unit, Windows.h + CRT only.
REM  It is NOT built by `npm run dist:installer`, so without this step the
REM  packaged client ships whatever injector.exe happens to be lying in assets\.
REM  Console subsystem is deliberate: it prints a JSON result line, and it is
REM  spawned with windowsHide so no window appears.
echo [3/6] Building injector.exe...
if not exist "%ROOT%internal\tools\injector\injector.cpp" (
  echo   [ERROR] internal\tools\injector\injector.cpp not found. & goto :fail
)
pushd "%ROOT%client\assets"
REM  UNICODE is required: injector.cpp calls LookupPrivilegeValueW but passes
REM  SE_DEBUG_NAME, a TCHAR macro that expands narrow without it, so the file
REM  will not compile. VS C++ projects define it by default; bare cl does not.
REM  advapi32 for the token APIs (OpenProcessToken, AdjustTokenPrivileges,
REM  LookupPrivilegeValueW); everything else in the file is kernel32.
cl /nologo /O2 /MT /W3 /EHsc /std:c++17 /DWIN32_LEAN_AND_MEAN /DUNICODE /D_UNICODE ^
   "%ROOT%internal\tools\injector\injector.cpp" /Fe:injector.exe ^
   /link advapi32.lib || ( popd & goto :fail )
del /q injector.obj 2>nul
popd
if not exist "%ROOT%client\assets\injector.exe" ( echo   [ERROR] injector.exe not produced. & goto :fail )
echo   Staged -^> client\assets\injector.exe

REM --- [4/6] Client dependencies ---------------------------------------------
pushd "%ROOT%client"
if not exist "node_modules\.bin\tsc.cmd" (
  echo [4/6] Installing client dependencies ^(npm install^)...
  call npm install || ( popd & goto :fail )
) else (
  echo [4/6] node_modules present - skipping npm install.
)

REM --- [5/6] Optional game XML -----------------------------------------------
if /I "%RE_SKIP_XML%"=="1" (
  echo [5/6] Skipping game-XML download ^(RE_SKIP_XML=1^).
) else (
  echo [5/6] Downloading game XML ^(best-effort^)...
  call npm run download-game-xml -- --dir ./data
  call npm run download-game-xml
)

REM --- [6/6] Package client ---------------------------------------------------
if /I "%MODE%"=="portable" (
  echo [6/6] Packaging client ^(portable^)...
  call npm run dist:portable
) else (
  echo [6/6] Packaging client ^(installer + portable^)...
  call npm run dist
)
if errorlevel 1 ( popd & goto :fail )
popd

echo.
echo ==================== BUILD OK ====================
echo Output: %ROOT%client\release
dir /b "%ROOT%client\release\*.exe" 2>nul
echo.
endlocal & exit /b 0

:fail
echo.
echo ==================== BUILD FAILED ====================
echo See the first error above.
endlocal & exit /b 1
